### ISSUE TITLE
Demo website - Update on 16th Aug

### ISSUE THREAD

**Issue by mshkanth** [AgnostiqHQ/covalent#1012]
**Decsription**
Placeholder to update the demo website with the latest version on `/develop`.
Tentatively planned for Aug 16th

**Comment by mshkanth** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Psi-Engineers-6220381c7f976300196f8756/issues/AgnostiqHQ/covalent/1012?planning-poker) with ZenHub @Prasy12

**Comment by Prasy12** [comment]
@wjcunningham7 @santoshkumarradha The current version of demo website has the all the up to date versions except only a couple of UI fixes.
Since there is a lot of code structural changes we are looking at making sure that the demo website branch aligns with the current develop branch which might take a bit more time than usual. We will look at definitely updating everything before your original release.
