### ISSUE TITLE
Reduce memory usage during postprocessing

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#1429]
The current implementation of postprocessing consumes memory needlessly. **Two** [copies of each intermediate output](https://github.com/AgnostiqHQ/covalent/blob/f1df14d57761723a4cf0871f8f117a23759f1b39/covalent_dispatcher/_core/execution.py#L157) are [serialized and passed](https://github.com/AgnostiqHQ/covalent/blob/f1df14d57761723a4cf0871f8f117a23759f1b39/covalent_dispatcher/_core/execution.py#L555) to the postprocessing function; note that the lattice argument already contains all intermediate outputs in its transport graph. For workflows with many large intermediate outputs, this inefficiency can nearly double the memory pressure on both the Covalent server and the postprocessor, potentially causing postprocessing to fail.

Some possible improvements include:

1. Since the `Result` object also has a `post_process` method, just send the `Result` object to the postprocessor and invoke `Result.post_process()` inside the postprocesor.

2. Replace the "Lattice" argument to `_postprocess` with just the serialized workflow function, construct a new Lattice inside the postprocessor from just the workflow function (empty transport graph), and set the `self.electron_outputs` attribute with the list of intermediate outputs.

Either of these would eliminate the duplicate copy of each intermediate output.

**Comment by madhur-tandon** [comment]
I guess the implementation has changed slightly since this issue was opened, but to summarise:

Initialising an object of `Postprocessor` has the `lattice` with it by the virtue of the following constructor:

```
class Postprocessor:
    def __init__(self, lattice) -> None:
        self.lattice = lattice
```

Also, the `_postprocess` function takes in `*ordered_node_outputs` which can be constructed from the `lattice` itself i.e. we have the following currently:

```
def _postprocess(self, *ordered_node_outputs: List[Any]) -> Any:
```
---
Now, the `Result` class also has the `_lattice` with it, owing to the following constructor:

```
def __init__(self, lattice: Lattice, dispatch_id: str = "") -> None:
    ....
    self._lattice = lattice
    ....
```

and the `post_process` function constructs the `ordered_node_outputs` by itself with the help of the underlying `_lattice`.

Note that, after we construct the `ordered_node_outputs`, the snippet that follows is an exact replica of whatever is present in `_postprocess` method of the `Postprocessor` class i.e.

https://github.com/AgnostiqHQ/covalent/blob/develop/covalent/_results_manager/result.py#L328-L336

is same as

https://github.com/AgnostiqHQ/covalent/blob/develop/covalent/_workflow/postprocessing.py#L101-L109

Clearly, there is code duplication.

---

To avoid code duplication, there are two potential solutions:

1. Use `Postprocessor` inside the `post_process` function of the `Result` class i.e. have

```
# result.py
def post_process(self) -> Any:
    ordered_node_outputs = .... # determine using self._lattice
    pp = Postprocessor(self._lattice)
    return pp._postprocess(ordered_node_outputs)
```

OR perhaps have...
2. Use `Result` inside `_postprocess` method of the `Postprocessor` class i.e.

```
# postprocessing.py
def _postprocess(self, result: Result) -> Any: # change the signature to accept an object of `Result` instead
    return result.post_process()
```
---

Clearly, both of them DON'T solve the issue of memory usage since using either of (1) or (2) forces us to have both objects i.e. an object of `Postprocessor` class as well as an object of `Result` class -- both of which have the `lattice` with them i.e. double memory consumption.

---

Another idea that comes to mind is to perhaps change the signature of `_postprocess` method of the `Postprocessor` class i.e. to have:

```
def _postprocess(self) -> Any:
    ....
    ordered_node_outputs = .... # calculate using self.lattice instead of receiving it as arguments
```

But then, this leads to even more code duplication since the `_postprocess` method of the `Postprocessor` class now resembles `post_process` method of the `Result` class even more...

---

In retrospect, we should evaluate if:

a. The current level of code duplication is acceptable or not?
b. Do we need to use `Postprocessor` and `Result` classes together in any way? Given that this won't solve memory consumption but will reduce code duplication.
c. Do we need the ability to post process from both `Postprocessor` and `Result`? This is related to (a). I ask since I am not sure if `_postprocess` method of the `Postprocessor` class is used anywhere right now, apart from tests. Perhaps we can eliminate it altogether?

Could appreciate your thoughts @cjao

**Comment by kessler-frost** [comment]
Closing as this is most likely resolved by the new memory improvements.
