### ISSUE TITLE
Update Twitter logo to X

### ISSUE THREAD

**Issue by blindaks** [AgnostiqHQ/covalent#1806]
### What should we add?

We should change the twitter logo in the footer from the old bird to new X.

**Comment by blindaks** [comment]
Please assign this issue to me.

**Comment by joshijoe05** [comment]
Hello, i would like to work on this issue,
Can you assign me?

**Comment by Min2who** [comment]
can you please assign me this issue i can make thus PR within an hour after you assign me this

**Comment by kessler-frost** [comment]
Hey guys, thanks a lot for your interest in this. Just a couple things to keep in mind for this one,
a) Assignment of an issue isn't a requirement for working on it and you can directly submit a PR linked to this issue to resolve it,
b) This will not be considered part of Hacktoberfest because of two reasons: 
    - We haven't added the appropriate label to it, i.e. we don't want it to be a part of Hacktoberfest
    - Issues/PRs like these are considered low effort as mentioned in the Hacktoberfest guidelines [here](https://hacktoberfest.com/participation/#spam)

That said, as always, we do appreciate the help if you want to update the Twitter logo to its new version.

**Comment by kessler-frost** [comment]
Actually, on second thought I'm gonna close this issue as something that we are not planning to change in the near future. We're quite fond of Larry.

In case you guys are still interested in contributing please take a look some of our other Hacktoberfest issues [here](https://github.com/AgnostiqHQ/covalent/labels/hacktoberfest).
