### ISSUE TITLE
Support for pennylane >=0.33.0

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [AgnostiqHQ/covalent#1871]
### What should we add?

https://github.com/AgnostiqHQ/covalent/issues/1845#issue-1985069011

> Recently, Pennylane has removed the operations attribute from their DefaultQubit class which means the following error might be thrown for users installing covalent in a new environment [with pennylane >= 0.33.0]: `AttributeError: type object 'DefaultQubit' has no attribute 'operations'`

Because of the above issue, the maximum version of pennylane is fixed (which also fixes the maximum version of numpy as a result). I'm opening an issue just so this is logged somewhere.

**Comment by Andrew-S-Rosen** [comment]
Looks like this is the offending line: https://github.com/AgnostiqHQ/covalent/blob/e45bd30d38aa4ee339a1a4b8fd3393a6d21c00d2/covalent/_workflow/qdevice.py#L45

**Comment by kessler-frost** [comment]
@Andrew-S-Rosen so when creating a new device in Pennylane there are some attributes that the custom device is required to have, essentially describing what are all the operations and observables that this particular device supports as not all devices can physically support all operations/observables. This is why here we are simply making our device support whatever the default device supports. This is why you couldn't find it in the codebase :sweat_smile: because it's something that is required by pennylane when defining a custom device.

**Comment by Andrew-S-Rosen** [comment]
@kessler-frost: Ah, that explains it! So then in order to resolve this issue, we basically need to swap out the required attributes (if any) and then would need to pin a lower-bound version on pennylane if I understand correctly.

**Comment by kessler-frost** [comment]
That is correct.

**Comment by kessler-frost** [comment]
Sorry @Andrew-S-Rosen , but I think this issue will be blocked by #1877 😓 . We don't currently have tests enabled for the qelectrons (which are the reason behind the Pennylane dependency), thus we cannot know whether upgrading to version 33 will break the feature or not (or if the feature has gotten broken due to a recent change yet).

**Comment by Andrew-S-Rosen** [comment]
@kessler-frost: Makes perfect sense to me! I was admittedly relying blind on the test suite for this since I don't know anything about pennylane. I'll go ahead and close this!
