### ISSUE TITLE
Sublattices should inherit the executor from the parent lattice if none is provided

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#417]
A user should be able to assign an executor to a lattice and that should be used for those electrons which do not have an explicitly assigned executor.

Edit: This seems to have resolved for other cases due to changes to the codebase but still remains an issue with sublattices.

**Comment by cjao** [comment]
I was just bitten by this. Now that we're defaulting to the Dask executor, I want to avoid some of the known issues (such as [this one](https://github.com/AgnostiqHQ/covalent/issues/638) and [this one](https://github.com/AgnostiqHQ/covalent/issues/611))  making some workflows run locally. However, setting `executor="local"` at the lattice level doesn't always work. For instance, it doesn't seem to get propagated to sublattices.

**Comment by santoshkumarradha** [comment]
@cjao Can you link these issues maybe ?

**Comment by wjcunningham7** [comment]
@kessler-frost is this resolved?

**Comment by kessler-frost** [comment]
@wjcunningham7  No, this has not been resolved afaik. Sublattices still don't respect the executor assignment. I'm changing the title for this.

**Comment by cjao** [comment]
Executor inheritance actually seems broken in general, not just for sublattices. There are a few separate technical issues:

### 1)  

In the [current implementation](https://github.com/AgnostiqHQ/covalent/blob/d893adbaec8a91c192db7707131c814d5862d489/covalent/_workflow/electron.py#L324-L330), an electron only inherits metadata from its enclosing lattice if the electron's metadata is already set to its default value. 

**1a)** The implementation doesn't work because the test `self.get_metadata(k) is DEFAULT_METADATA_VALUES[k]` is too strict. The `is` keyword tests if both sides are the same Python object, whereas we merely intend to test whether they represent the same value. For example (default executor is `"local"`)

```python
@ct.electron
def task(x):
    return x

@ct.lattice(executor="awslambda")
def workflow(x):
    return task(x)

workflow.build_graph(1)
```
(Debug statements added)
```
k not in consumable_constraints:  True
k in DEFAULT_METADATA_VALUES:  True
self.get_metadata(k) is DEFAULT_METADATA_VALUES[k]:  False
self.get_metadata(k) == DEFAULT_METADATA_VALUES[k]:  True
self.get_metadata(k),  DEFAULT_METADATA_VALUES[k]: local , local
```
```
>>>print(workflow.metadata["executor"])
```
```
awslambda
```
The electron fails to inherit  `awslambda` from the lattice:
```
>>>print(workflow.transport_graph.get_node_value(0, "metadata")["executor"])
```

```
local
```

**1b)** Even if the `is` were changed to `==`, a different scenario would still be broken: even if the electron explicitly specifies the default executor, its executor would still be overridden by the Lattice's:


```python
# User wants the default "local" executor for this electron
@ct.electron(executor="local")
def task(x):
    return x

@ct.lattice(executor="awslambda")
def workflow(x):
    return task(x)

workflow.build_graph(1)
```

Here, I've changed `is` to `==` in the test; the electron's "local" executor is incorrectly overridden by the Lattice's executor:
```
>>>print(workflow.metadata["executor"], print(workflow.transport_graph.get_node_value(0, "metadata")["executor"])
```
```
awslambda awslambda
```

One way to fix both of these scenarios is to initialize all electron metadata to `None` by default and then copy the Lattice metadata only for those electron fields that aren't specified by the user:
```python
# Lattice respects explicit executor settings
@ct.electron(executor="local")
def task(x):
    return x

@ct.lattice(executor="awslambda")
def workflow(x):
    return task(x)

workflow.build_graph(1)
print(workflow.metadata["executor"], workflow.transport_graph.get_node_value(0, "metadata")["executor"])
```
```
awslambda local
```

```python
# executor is initialized to None and set during build_graph from the Lattice's
@ct.electron
def task(x):
    return x

@ct.lattice(executor="awslambda")
def workflow(x):
    return task(x)

workflow.build_graph(1)
print(workflow.metadata["executor"], workflow.transport_graph.get_node_value(0, "metadata")["executor"])
```
```
awslambda awslambda
```

```python
# executor is initialized to None and set during build_graph from the Lattice's
@ct.electron
def task(x):
    return x

# Lattice's executor defaults to the default executor ("local" in this case)
@ct.lattice
def workflow(x):
    return task(x)

workflow.build_graph(1)
print(workflow.metadata["executor"], workflow.transport_graph.get_node_value(0, "metadata")["executor"])
```
```
awslambda awslambda
```

**Comment by cjao** [comment]
### 2) Sublattices without explicitly specified executors don't inherit the parent lattice's executor.

Lattice-level metadata are currently populated with their default values in the [lattice decorator](https://github.com/AgnostiqHQ/covalent/blob/develop/covalent/_workflow/lattice.py#L307). 

3.1) As above, we can set the Lattice-metadata's default values to `None` and replace any unset metadata fields with their values from `DEFAULT_METADATA_VALUES`  at the beginning of `build_graph()`. 

3.2) When a sublattice is initially encountered during workflow execution, its unset metadata fields will be `None` since its graph has not yet been built. One can pass the parent lattice's metadata as an argument to the [out-of-process call](https://github.com/AgnostiqHQ/covalent/blob/d893adbaec8a91c192db7707131c814d5862d489/covalent_dispatcher/_core/execution.py#L191) to `_build_sublattice_graph()`, and replace any unset sublattice metadata, something like

```python
def _build_sublattice_graph(parent_lattice, sublattice, *args, **kwargs):
    for k in sublattice.metadata.keys():
        if sublattice.metadata[k] is None:
                sublattice.metadata[k] = parent_lattice.metadata[k]
    sublattice.build_graph(*args, **kwargs)
   ...
```

**Comment by wjcunningham7** [comment]
discussion carried forward in #1284

**Comment by kessler-frost** [comment]
>Proposal: One way to fix both of these scenarios is to initialize all electron metadata to None by default and then, during build_graph(), copy the Lattice metadata only for those electron fields that aren't specified by the user. This change results in the expected behavior for all three of the following examples:

I like this proposed solution.
