### ISSUE TITLE
Improve `get_result` method

### ISSUE THREAD

**Issue by venkatBala** [AgnostiqHQ/covalent#483]
* Optimize get result so that we are not constantly unpickling the result object

**Comment by kessler-frost** [comment]
In `get_result` function of `covalent/_results_manager/results_manager.py` we're using `_get_result_from_file` which unnecessarily does the unpickling of the result object in a `while True:` loop just to read a single status attribute, as such:

```python
while True:
      try:
          with open(os.path.join(result_dir, "result.pkl"), "rb") as f:
              result = pickle.loads(f.read())

          if not wait:
              return result
          elif result.status in [Result.COMPLETED, Result.FAILED, Result.CANCELLED]:
              return result
      except (FileNotFoundError, EOFError, _pickle.UnpicklingError):
          if wait:
              continue
          raise RuntimeError(
              "Result not ready to read yet. Please wait for a couple of seconds."
          )
```

This makes getting the result with `wait=True` really slow and consequently impacts the performance of `dispatch_sync` (and covalent overall).

We can probably solve this by just adding a `get_status` endpoint to the dispatcher which can get queried periodically, and when the status is `Result.COMPLETED` only then it tries to unpickle, load, and return the result object. In order to do that we may want to maintain a shared dictionary which stores the status of every workflow received, since it will have to be thread safe, I recommend using a `multiprocessing.Queue` to store that dictionary.

There can be a better solution for which I'm all ears.

**Comment by anushkrishnav** [comment]
I would like to work on this issue, we can explore multi-processing for this or celery. I have experience working with both of them

**Comment by kessler-frost** [comment]
Hi @anushkrishnav! We're glad that you'd like to contribute to us.

For this issue we'd want to avoid using another thread/process other than the resources already being used by Flask. I was thinking more along the lines of having an API endpoint which `ct.get_result` queries to and it checks whether the result is ready to be returned. What do you think?

**Comment by anushkrishnav** [comment]
I will check it out today , i will be starting on the task tonight

**Comment by scottwn** [comment]
@anushkrishnav any progress on this issue? Feel free to open a draft PR if you would like us to look at your code.

**Comment by scottwn** [comment]
@kessler-frost do you still want to do this or would you like me to take it? I'm working on similar stuff today

**Comment by kessler-frost** [comment]
@scottwn You can take this if you like, I'm working on something unrelated to this right now.

**Comment by scottwn** [comment]
This is resolved.
- `_get_result_from_file` was removed in https://github.com/AgnostiqHQ/covalent/commit/5b11092a4f738071fcb4cf29a4002a74b18be262#diff-5694ed1aa0e5cf6e57cf19bb998f92485940c7df6209fa3b0d719a33fbb38802L67
- `GET` `/result/<dispatch_id>` accepts a `status_only` query param, if `true` it doesn't do any pickling.
https://github.com/AgnostiqHQ/covalent/blob/a1a87708eaa4da01dd4cc799e0014b1b98e9b61f/covalent_dispatcher/_service/app.py#L124-L127
