### ISSUE TITLE
Unable to use IBM qiskit and Rigetti forest plugins with Pennylane

### ISSUE THREAD

**Issue by poojithurao** [AgnostiqHQ/covalent#603]
### Environment

- **Covalent version**: 0.106.0
- **Python version**: 3.8.13
- **Operating system**: Ubuntu 18.04.6 LTS

### What is happening?

I am trying to use different devices with Pennylane with the help of different device plugins. I am able to use these devices properly when I run the code without covalent. However, when I tried it with covalent they are throwing different errors for each device.

With `dev0 = qml.device("forest.qvm", device="4q-qvm")` I am getting `TypeError: no default __reduce__ due to non-trivial __cinit__` error 

With `dev1 = qml.device("qiskit.aer", wires=4)` I am getting `HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://0.0.0.0:48008/api/submit` error.

Look into the code in the following section.

### How can we reproduce the issue?

```
import pennylane as qml
from pennylane import numpy as np
import covalent as ct

dev0 = qml.device("forest.qvm", device="4q-qvm")
dev1 = qml.device("qiskit.aer", wires=4)
dev2 = qml.device("default.qubit", wires=4)


@ct.electron
@qml.qnode(dev1)
def qubit_rotation(phi1):
    qml.RX(phi1, wires=0)
    return qml.expval(qml.PauliZ(0))

@ct.lattice
def workflow(phi):
    res = qubit_rotation(phi)
    return res


dispatch_id = ct.dispatch(workflow)(0)
```

By replacing the 'dev' in `@qml.qnode(dev)` the above-mentioned errors can be reproduced.

### What should happen?

A float value must be returned as an answer.

**Comment by santoshkumarradha** [comment]
Hi @poojithurao ,

Since `dev2` `default.qubit` works, i suspect its something to do with Pickling with the other plugins. While we expect someone to resolve this soon, I would strongly recommend the following pattern over the one you have for constructing workflows

```python
import pennylane as qml
from pennylane import numpy as np
import covalent as ct




@ct.electron
def get_circuit(dev):
    
    @qml.qnode(dev)
    def qubit_rotation(phi):
        qml.RX(phi, wires=0)
        return qml.expval(qml.PauliZ(0))
    
    return qubit_rotation

@ct.electron
def qubit_rotation(circuit, phi):
    return circuit(phi)

@ct.lattice
def workflow(phi,dev):
    circuit=get_circuit(dev)
    res = qubit_rotation(circuit,phi)
    return res


dev = qml.device("default.qubit", wires=4)
dispatch_id = ct.dispatch(workflow)(phi=0.5,dev=dev)
```

- This is because, you want `dev` to be a parameter you change on the fly for your workflows, i.e want to do the following `ct.dispatch(workflow)(phi=0.5,dev=dev) for dev in [dev1,dev2,dev3]` 
- and also, you are referencing a global variable `dev1,dev2,dev3` in your workflow, which would definitely work, but is not ideal as when saving the workflow, you loose the variables definition, i.e if you look at your `dispatch_source.py` generated, you wont have the information for `dev` when you do it in your pattern as dev is a global variable that is not saved by covalent.

**Comment by poojithurao** [comment]
Hey @santoshkumarradha, thanks, noted and will take care of that.
