### ISSUE TITLE
Passing the executor="local" parameter to an electron when running Covalent with Dask does not result in local execution

### ISSUE THREAD

**Issue by Emmanuel289** [AgnostiqHQ/covalent#699]
### Environment

- **Covalent version**: 0.110.0
- **Python version**: 3.8.13
- **Operating system**: Linux/MacOS

### What is happening?

Passing the executor="local"  parameter to an electron when running Covalent with Dask does not result in local execution. 

### How can we reproduce the issue?

With `covalent start`,  Dask overrides execution of an electron that is decorated with the "local" executor. 

### What should happen?

Passing the parameter executor="local" to an electron when running Covalent with Dask should execute the electron locally.

**Comment by cjao** [comment]
This is odd, I was using `executor="local"` to work around [the Dask serialization bug](https://github.com/AgnostiqHQ/covalent/issues/638#issuecomment-1154469766). Can you provide a test script?

I do notice that specifying `executor="local"` at the lattice level sometimes fails to propagate to electrons, but that issue is [already being tracked](https://github.com/AgnostiqHQ/covalent/issues/417).

**Comment by santoshkumarradha** [comment]
@Emmanuel289  any chance you tried passing `Local` object instead of string ?
