### ISSUE TITLE
Removing post processing

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#941]
The problems that post processing is solving can be solved without running through the entire function a 3rd time.

For example, the main reason for doing post processing is to determine what will be returned at the end of the lattice function execution. Those things can be determined during build graph time as well since we are anyways going through the function once.

This is not a trivial task and will require a lot of discussion before coming to a solution.

**Comment by kessler-frost** [comment]
Reasoning on why we want to remove post processing:

>Currently we have two options, the user can postprocess either locally or pass on an executer to postprocess. Initial intend of postprocessing was a quick and dirty way to get the final return objects instead of writing a clever algorithm to do it before hand. Now since we require resources to post process, we may as well write the algorithm to get the return values when preprocessing. Down side is that certain things that can be done in lattice are lost (as for now, the only certain thing that is lost is printing inside lattice with "postprocessed" result variables, rest are already things that cannot be done in lattice). With this, considering we are not loosing much by not printing post processed result inside lattice, we can opt for removing post process and adding in return variable in preprocess step as requiring additional resource with installed packages for postprocessing is a very heavy requirement

**Comment by cjao** [comment]
One way to resolve the return value of a workflow without running through the entire workflow function is to introduce a `ct.resolve()` function which takes as input an electron and returns either
* the electron's output if invoked in the context of an active lattice in postprocessing mode; in this case the electron is bound to a node in the transport graph, so one just returns the output of the corresponding node
* the electron itself otherwise.

Then if the user applies `ct.resolve()` to each electron appearing in the workflow function's return value, "postprocessing" can be reduced to simply evaluating the workflow function's return value stored during build-graph.

```python
@ct.lattice
def workflow():
    res1 = task_1()
    res2 = task_2()
   return ct.resolve(res1), ct.resolve(res2)
```
Not the prettiest UI, but 
* it does avoid having to deserialize the workflow function.
* it doesn't compromise the ability to call `workflow`.
* it can be implemented in a day.

**Comment by santoshkumarradha** [comment]
@mshkanth this might be of help to you.

**Comment by mshkanth** [comment]
> @mshkanth this might be of help to you.

As of now, we are anyway going ahead and showing the 3 post processed statuses as 'Completed' on the GUI

**Comment by santoshkumarradha** [comment]
Closing as duplicate
